; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:nodemcu-32s]
platform = espressif32
board = nodemcu-32s
framework = arduino
monitor_speed = 115200
build_src_filter = +<*> -<energy_monitor.cpp>
; --- 3. LIBRARY DEPENDENCIES ---
; PlatformIO will automatically download these when you build.
lib_deps = 
    SPI
    Wire
    knolleary/PubSubClient @ ^2.8
    kosme/arduinoFFT @ ^2.0.4
    kosme/ArduinoFFT @ ^2.0.4
    arduinoFFT @ ^2.0.4


[env:raspberry-pi-pico]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = pico
framework = arduino
board_build.core = earlephilhower
build_flags =
    -DPIO_FRAMEWORK_ARDUINO_ENABLE_CDC
    -DUSBCON
monitor_speed = 115200
;upload_speed = 921600
build_src_filter = +<generator_monitor.cpp>
;monitor_port = COM5
;upload_port = COM4
upload_protocol = picotool ; cmsis-dap, jlink, mbed, picotool, raspberrypi-swd
lib_deps =
    SPI
    Wire
    adafruit/Adafruit BusIO@^1.16.1
    adafruit/Adafruit INA219@^1.2.1